name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: install puppeteer
        run: deno install --allow-scripts=npm:puppeteer@24.10.0
      - name: publish to JSR
        run: npx jsr publish

      
