name: Update

on:
  #schedule:
  #  - cron: "0/15 * * * *"
  #workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/version-checker

    steps:
      - uses: actions/checkout@v4

      - name: Install node v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Deno v2
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: npm install

      - name: Run Updater
        run: ./update-version

      - name: Store WA Version
        run: echo WA_VERSION=`cat ./.version` >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-wa-web-update/patch
          delete-branch: true
          commit-message: Update supported WhatsApp Web version to v${{ env.WA_VERSION }}
          title: Update WhatsApp Web Version (${{ env.WA_VERSION }})
          body: |
            A new version of WhatsApp Web has been detected! 
            
            Tests should be run against this new version before merging.
          labels: WhatsApp Change
          reviewers: pedroslopez
